title: Kelvin Waters # your name (or website title) here
logo: "/images/Kelvin Cropped.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data scientist who excels at exploratory data analysis, machine learning, and conveying those results to non-technical clients through the use of visualizations. I am dependable and focused, utilizing valued communication skills in order to convey technical results to non-technical clients and business partners. 
  <br><br>
  I have a bachelors degree in computer science from Everest University and completed the immersive full-time data science course with the Flatiron School of NYC. I welcome the time to further discuss a full-time data science opportunity in a positive environment and can be reached either through this profile or by phone at 813-770-7559. 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
